# Import Libraries

In [47]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Normalizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

# Load Dataset

In [3]:
dataset = pd.read_csv(r'E:\PYTHONCLASSJUPYTER\PrakashSenapati\2024_10_17_Naive Bayes Theorem\Social_Network_Ads.csv')

In [4]:
dataset.shape

(400, 5)

In [5]:
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

# Filter Feature (X) and Target (y) Variables

In [6]:
X = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, -1].values

In [7]:
X[0:10]

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000]], dtype=int64)

In [8]:
y[0:10]

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int64)

In [9]:
print(X.shape)
print(y.shape)

(400, 2)
(400,)


# Split Dataset into the Training and Testing Set

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

In [11]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(320, 2)
(80, 2)
(320,)
(80,)


In [12]:
X_train[0:10]

array([[    58, 144000],
       [    59,  83000],
       [    24,  55000],
       [    26,  35000],
       [    58,  38000],
       [    42,  80000],
       [    40,  75000],
       [    59, 130000],
       [    46,  41000],
       [    41,  60000]], dtype=int64)

In [14]:
X_test[0:10]

array([[    30,  87000],
       [    38,  50000],
       [    35,  75000],
       [    30,  79000],
       [    35,  50000],
       [    27,  20000],
       [    31,  15000],
       [    36, 144000],
       [    18,  68000],
       [    47,  43000]], dtype=int64)

In [13]:
y_train[0:10]

array([1, 0, 0, 0, 1, 1, 0, 1, 1, 0], dtype=int64)

In [15]:
y_test[0:10]

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int64)

# Feature Scaling

In [16]:
sc = Normalizer()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
print(X_train.shape)
print(X_test.shape)

(320, 2)
(80, 2)


In [18]:
print( X_train[0:10] )

[[4.02777745e-04 9.99999919e-01]
 [7.10843194e-04 9.99999747e-01]
 [4.36363595e-04 9.99999905e-01]
 [7.42856938e-04 9.99999724e-01]
 [1.52631401e-03 9.99998835e-01]
 [5.24999928e-04 9.99999862e-01]
 [5.33333257e-04 9.99999858e-01]
 [4.53846107e-04 9.99999897e-01]
 [1.12195051e-03 9.99999371e-01]
 [6.83333174e-04 9.99999767e-01]]


In [19]:
print( X_test[0:10] )

[[3.44827566e-04 9.99999941e-01]
 [7.59999781e-04 9.99999711e-01]
 [4.66666616e-04 9.99999891e-01]
 [3.79746808e-04 9.99999928e-01]
 [6.99999829e-04 9.99999755e-01]
 [1.34999877e-03 9.99999089e-01]
 [2.06666225e-03 9.99997864e-01]
 [2.49999992e-04 9.99999969e-01]
 [2.64705873e-04 9.99999965e-01]
 [1.09302260e-03 9.99999403e-01]]


# Naive Bayes - MultinomialNB

In [20]:
mnb_classifier = MultinomialNB() 
mnb_classifier.fit(X_train, y_train)

MultinomialNB()

In [21]:
y_pred_mnb = mnb_classifier.predict(X_test)
y_pred_mnb.shape

(80,)

In [22]:
print( y_pred_mnb )

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0]


In [23]:
bias_mnb = mnb_classifier.score(X_train, y_train)
bias_mnb

0.621875

In [24]:
variance_mnb = mnb_classifier.score(X_test, y_test)
bias_mnb

0.621875

In [27]:
cm_mnb = confusion_matrix(y_test, y_pred_mnb)
print(cm_mnb)

[[58  0]
 [22  0]]


In [28]:
ac_mnb = accuracy_score(y_test, y_pred_mnb)
print(ac_mnb)

0.725


In [48]:
cr_mnb = classification_report(y_test, y_pred_mnb)
print(cr_mnb)

              precision    recall  f1-score   support

           0       0.72      1.00      0.84        58
           1       0.00      0.00      0.00        22

    accuracy                           0.72        80
   macro avg       0.36      0.50      0.42        80
weighted avg       0.53      0.72      0.61        80



# Naive Bayes - GaussianNB

In [31]:
gnb_classifier = GaussianNB() 
gnb_classifier.fit(X_train, y_train)

GaussianNB()

In [32]:
y_pred_gnb = gnb_classifier.predict(X_test)
y_pred_gnb.shape

(80,)

In [33]:
print( y_pred_gnb )

[0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 1 0]


In [34]:
bias_gnb = gnb_classifier.score(X_train, y_train)
bias_gnb

0.671875

In [35]:
variance_gnb = gnb_classifier.score(X_test, y_test)
variance_gnb

0.725

In [36]:
cm_gnb = confusion_matrix(y_test, y_pred_gnb)
print(cm_gnb)

[[52  6]
 [16  6]]


In [37]:
ac_gnb = accuracy_score(y_test, y_pred_gnb)
print(ac_gnb)

0.725


In [38]:
cr_gnb = classification_report(y_test, y_pred_gnb)
print(cr_gnb)

              precision    recall  f1-score   support

           0       0.76      0.90      0.83        58
           1       0.50      0.27      0.35        22

    accuracy                           0.72        80
   macro avg       0.63      0.58      0.59        80
weighted avg       0.69      0.72      0.70        80



# Naive Bayes - BernoulliNB

In [39]:
bnb_classifier = BernoulliNB() 
bnb_classifier.fit(X_train, y_train)

BernoulliNB()

In [40]:
y_pred_bnb = mnb_classifier.predict(X_test)
y_pred_bnb.shape

(80,)

In [41]:
print(y_pred_bnb )

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0]


In [42]:
bias_bnb = bnb_classifier.score(X_train, y_train)
bias_bnb

0.621875

In [43]:
variance_bnb = bnb_classifier.score(X_test, y_test)
variance_bnb

0.725

In [44]:
cm_bnb = confusion_matrix(y_test, y_pred_bnb)
print(cm_bnb)

[[58  0]
 [22  0]]


In [45]:
ac_bnb = accuracy_score(y_test, y_pred_bnb)
print(ac_bnb)

0.725


In [49]:
cr_bnb = classification_report(y_test, y_pred_bnb)
print(cr_bnb)

              precision    recall  f1-score   support

           0       0.72      1.00      0.84        58
           1       0.00      0.00      0.00        22

    accuracy                           0.72        80
   macro avg       0.36      0.50      0.42        80
weighted avg       0.53      0.72      0.61        80

